### ISSUE TITLE
Problema com o botão de cadastro - 08-crud

### ISSUE THREAD

**Issue by ErikFerreira477** [fernandoleonid/mini-projetos-js#1]
Boa noite professor, estava estudando pelo seu video e fiz alguns testes no código. Reparei que se você tentar cadastrar um usuário após editar qualquer linha da tabela o cadastro para de funcionar e fica apenas editando a ultima linha que foi alterada.

**Comment by fernandoleonid** [comment]
- [x] Verificar o estado quando editamos algum cliente.
