### ISSUE TITLE
Problema com a responsividade

### ISSUE THREAD

**Issue by CristianoSFMothe** [fernandoleonid/mini-projetos-js#2]
Olá boa noite!!!
Estou amando seu projeto, mas estou com um pequeno problema com relação a responsividade dele. estou tentando fazer ela, mas estar desconfigurando o projeto todo.
Poderia me dar uma dica?

https://github.com/CristianoDaSilvaFerreira/Sistema-Cadastro-Cliente-JavaScript

**Comment by fernandoleonid** [comment]
Olá!
Não sei se vc já resolveu, mas eu vi seu projeto e não consegui perceber onde está quebrando a responsividade.

**Comment by CristianoSFMothe** [comment]
Fernando boa tarde!!!

Consiguir resolver não, quando vai diminuindo as dimensões da tela o layout vai quebrando

**Comment by fernandoleonid** [comment]
Cristiano, olha não consegui ver porque o seu está com esse erro.
Mas para resolver é só dar um margin-top de 50px na classe records, ficando assim:
@media (max-width: 480px) {
    .records {
        margin-top: 50px;
        border-spacing: 5px;
        z-index: -1;
    }

Espero que ajude!
